"""Application use cases."""

from tsse.application.cargo_market import (
    CargoMarketEditorSession,
    CargoMarketEntry,
    CargoMarketError,
    CompanyIdentity,
    company_identity,
    list_companies,
    randomize_city,
    randomize_company,
    reset_city,
    reset_company,
    resolve_company,
)
from tsse.application.freight_market import (
    FreightMarketError,
    JobOfferPayload,
    clear_pending_jobs,
    expiration_time,
    resolve_job_offer,
    write_job_offer,
)
from tsse.application.garage_editor import find_garage, set_garage_status
from tsse.application.legacy_convoy import (
    LegacyConvoyError,
    copy_truck_position,
    paste_truck_position,
    set_truck_position,
)
from tsse.application.player_editor import (
    experience_to_level,
    level_to_experience,
    resolve_driver,
    set_company_name,
    set_experience,
    set_gender,
    set_hq_city,
    set_money,
    set_skill,
    unlock_dealer,
    unlock_recruitment,
    visit_city,
)
from tsse.application.profile_cloning import CloneResult, ProfileCloneError, ProfileCloner
from tsse.application.profile_identity import (
    DirectoryRenameResult,
    ProfileIdentityEditor,
    ProfileIdentityError,
    profile_directory_identity,
    replace_profile_name,
    validate_profile_name,
)
from tsse.application.profile_info import (
    InfoSiiModel,
    ProfileInfoError,
    ProfileInfoService,
    ProfileInfoWriteResult,
    ProfileSiiModel,
    parse_info_sii,
    parse_profile_sii,
    set_info_money_account,
)
from tsse.application.profile_settings_zip import ProfileSettingsZip, ProfileSettingsZipError
from tsse.application.save_edit_service import (
    ProductionSaveWriteResult,
    SaveEditError,
    SaveEditService,
    SaveStructureError,
)
from tsse.application.editor_service import (
    EditorSaveState,
    EditorService,
    CompanyEditorSession,
    GarageEditorSession,
    PendingChangeDecision,
    PlayerEditorSession,
    resolve_pending_change,
)
from tsse.application.current_save_context import CurrentSaveContext
from tsse.application.trailer_editor import (
    TrailerComponent,
    find_trailer,
    repair_trailer,
    repair_trailer_component,
)
from tsse.application.truck_editor import (
    TruckComponent,
    find_truck,
    refuel_truck,
    repair_truck,
    repair_truck_component,
    set_condition,
)

__all__ = [
    "CloneResult",
    "ProfileCloneError",
    "ProfileCloner",
    "ProfileIdentityEditor",
    "ProfileSettingsZip",
    "ProfileSettingsZipError",
    "InfoSiiModel",
    "ProfileInfoError",
    "ProfileInfoService",
    "ProfileInfoWriteResult",
    "ProfileSiiModel",
    "parse_info_sii",
    "parse_profile_sii",
    "set_info_money_account",
    "DirectoryRenameResult",
    "ProfileIdentityError",
    "find_truck",
    "TruckComponent",
    "find_garage",
    "find_trailer",
    "TrailerComponent",
    "repair_trailer",
    "repair_trailer_component",
    "set_condition",
    "repair_truck",
    "repair_truck_component",
    "refuel_truck",
    "set_garage_status",
    "set_experience",
    "set_gender",
    "set_company_name",
    "set_hq_city",
    "experience_to_level",
    "level_to_experience",
    "set_money",
    "set_skill",
    "unlock_dealer",
    "unlock_recruitment",
    "visit_city",
    "resolve_driver",
    "find_garage",
    "set_garage_status",
    "CargoMarketError",
    "CargoMarketEditorSession",
    "CargoMarketEntry",
    "CompanyIdentity",
    "company_identity",
    "list_companies",
    "randomize_city",
    "randomize_company",
    "reset_city",
    "reset_company",
    "resolve_company",
    "FreightMarketError",
    "JobOfferPayload",
    "clear_pending_jobs",
    "expiration_time",
    "resolve_job_offer",
    "write_job_offer",
    "LegacyConvoyError",
    "copy_truck_position",
    "paste_truck_position",
    "set_truck_position",
    "replace_profile_name",
    "profile_directory_identity",
    "validate_profile_name",
    "ProductionSaveWriteResult",
    "SaveEditError",
    "SaveEditService",
    "SaveStructureError",
    "EditorSaveState",
    "EditorService",
    "CompanyEditorSession",
    "GarageEditorSession",
    "PlayerEditorSession",
    "PendingChangeDecision",
    "resolve_pending_change",
    "CurrentSaveContext",
]
